version: 2.0

logger:
  level: INFO
  debug_file: 'debug.log'
  format: '%(asctime)-15s %(name)s %(message)s'

krc_rpc:
  hostname: 'PCRC-2RL7HHTTRE' # OfficeLite PC's hostname
  port: 3333 # must be same as in appsettings.json (listen port KRC-RPC)
  authkey: 'TOP_SECRET_KEY' # must be same as in appsettings.json (auth key KRC-RPC)
  reconnect_timeout: 30
  refresh_time: 0.0

robodk:
  robotname: 'KUKA KR 270 R2700 ultra' # Must be same as the robot's name in RoboDK station
  CNT: 10 # Also known as: CNT, APO/C_DIS, ZoneData, Blending radius, cornering
  speed: 1000 # Set linear speed in mm/s
  refresh_time: 0.0

plc:
  ip: 192.168.101.1 # PLC SIM ip address
  db_num: 1 # DB1 Don't forget to turn off optimezed block access! Settings - attributes
  reconnect_timeout: 30
  refresh_time: 0.0

  data_io:
    # Supported variables: Bool, Int, USInt, Real, Char, String
    # Use same offsets as in Data Block

    rdk_db_in: #RoboDK OUT variables
      LifeBit_RDK: [ False, "Bool", 0, 0 ]

      #CNC 1
      CNC1_Free: [ False, "Bool", 2, 0 ]
      CNC1_Busy: [ False, "Bool", 2, 1 ]
      CNC1_DoorClosed: [ False, "Bool", 2, 2 ]
      CNC1_DoorOpened: [ False, "Bool", 2, 3 ]
      CNC1_OUT_Reserve: [ False, "Bool", 2, 4 ]

      #CNC 2
      CNC2_Free: [ False, "Bool", 4, 0 ]
      CNC2_Busy: [ False, "Bool", 4, 1 ]
      CNC2_DoorClosed: [ False, "Bool", 4, 2 ]
      CNC2_DoorOpened: [ False, "Bool", 4, 3 ]
      CNC2_OUT_Reserve: [ False, "Bool", 4, 4 ]

    rdk_db_out: #RoboDK IN variables
      LifeBit_PLC: [ False, "Bool", 6, 0 ]

      #CNC 1
      CNC1_OpenDoor: [ False, "Bool", 8, 0 ]
      CNC1_CloseDoor: [ False, "Bool", 8, 1 ]
      CNC1_Start: [ False, "Bool", 8, 2 ]
      CNC1_Stop: [ False, "Bool", 8, 3 ]
      CNC1_IN_Reserve: [ False, "Bool", 8, 4 ]

      #CNC 2
      CNC2_OpenDoor: [ False, "Bool", 10, 0 ]
      CNC2_CloseDoor: [ False, "Bool", 10, 1 ]
      CNC2_Start: [ False, "Bool", 10, 2 ]
      CNC2_Stop: [ False, "Bool", 10, 3 ]
      CNC2_IN_Reserve: [ False, "Bool", 10, 4 ]

    kuka_db_out: #KUKA IN variables
      DEF_ADVANCE: [ 0, "UInt", 12, 0 ]

    kuka_db_in: #KUKA OUT variables
      $ACT_BASE: [0, "USInt", 14, 0]